TITLE = "Totmann"
START_BUTTON_TEXT = "Start"
RESET_BUTTON_TEXT = "Hier \nberühren !"
TIMEOUT_LABEL_TEXT = "Timeout (Minuten):"
COUNTDOWN_LABEL_TEXT = "Countdown (Minuten):"
ALARM_LABEL_TEXT = "Alarm (Minuten):"
ALARM_TEXT = " Alarm in {minutes:02d}:{seconds:02d}"
